version: 2

jobs:
  # Build & Deploy against development backend
  "build-dev":
    docker:
      - image: openjdk:7
    steps:
      # Initialization.
      - run:
          name: Installation of build dependencies.
          command: |
            apt update
            apt install -y  openssl ant git zip jq 
            cd /usr/share/ant/lib
            wget https://repo1.maven.org/maven2/org/codehaus/groovy/groovy-all/1.7.8/groovy-all-1.7.8.jar
            wget https://repo1.maven.org/maven2/ant-contrib/ant-contrib/1.0b3/ant-contrib-1.0b3.jar
            cd ~/project   
      - run:
          name: checking out build repo
          command: |
            git clone --branch master https://github.com/topcoder-platform/tc-deploy-scripts ../buildscript 
            #git clone --branch master git@github.com:appirio-tech/ops.git ../direct-config-update
            git clone --branch dev-circleci https://$GITUSER:$GITPASSWD@github.com/appirio-tech/tc-components.git ../tc-components 
            git clone --branch dev-circleci https://github.com/topcoder-platform/tc-online-review.git ../tc-online-review
      - checkout           
      - run:
          name: copying configuration file
          command: |
            cp ./../buildscript/autopilot/conf/dev/token.properties.enc .
            openssl enc -aes-256-cbc -d -in token.properties.enc -out token.properties -k $SECPASSWD 
            mv token.properties ./../tc-online-review/
      - run:
          name: Installation of build dependencies.
          command: |
            javac -version
            ant -version
            ant clean dist
      - store_artifacts:
          path: ~/tc-online-review/build/ant/auto_pilot/dist
workflows:
  version: 2
  build:
    jobs:
      # Development builds are executed on "develop" branch only.
      - "build-dev":
          filters:
            branches:
              only: dev-circleci		  


